import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@fortawesome/fontawesome-free/css/all.min.css";
import "./globals.css";
import Navbar from "./navbar/page";
import Footer from "./footer/page";
import AOSProvider from "../app/components/aosprovider"; // 👈 Import the new AOS client initializer

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

// ✅ Server Component – metadata export is fine
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="bg-gradient-to-r from-[#070121] to-[#170080]">
        <AOSProvider /> {/* ✅ AOS initialized on client side */}
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
